### ISSUE TITLE
Push BERT-base model failed

### ISSUE THREAD

**Issue by soiferj** [dmlc/web-data#205]
I am trying to create a TVM unit-test with BERT base, and I noticed that other .pb files used in unit tests are uploaded here. I created the model .pb, created a fork of this repo, but am unable to push to my remote branch because it exceeds GitHub's max file size of 100MB. The BERT .pb is 679MB. Is there any way around this? It would be really nice to add a BERT test in TVM.

@srkreddy1238 @tqchen do you have any thoughts?

Thanks!

**Comment by tqchen** [comment]
Is it possible to create a dummy version of equivalent computation in relay.testing and test out the capability for now?

**Comment by soiferj** [comment]
Yeah, I'm thinking about trying to manually reduce the BERT to 2 or 3 layers and see if that helps. If not, I'll just re-create the graph in relay.testing. Thanks for the reply.

**Comment by soiferj** [comment]
Turns out that doesn't help :( I'll close this issue and manually code the logic into tf.testing. Thanks!
