### ISSUE TITLE
TVM optimization for the yolov3-tiny network

### ISSUE THREAD

**Issue by rakshaachlady** [dmlc/web-data#210]
I am trying to optimise yolov3-tiny darknet model on jetson nano using TVM compiler. I tried to run the code as mentioned in the below URL.
https://docs.tvm.ai/tutorials/frontend/from_darknet.html#sphx-glr-tutorials-frontend-from-darknet-py 

It was throwing errors to download the weight and cfg files.So,I downloaded separately and gave the corresponding path.For downloading the darknet library it is throwing an error saying 'nonetype' content length in the url headers. Attached the screenshot below.
![download_error](https://user-images.githubusercontent.com/52130041/67197161-d36ce680-f419-11e9-9111-a6b99d61d533.png)

Can anyone help me in solving this issue??

I have also tried to download "libdarnet2.so" separately from the url and and tried to load.This time I am getting the error telling "cannot open shared object file.Additionally, "ctypes.util.find_library() did not manage to locate a library called libdarnet2.so" even though I mentioned the correct path for loading.

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.ai/
