### ISSUE TITLE
Typo in command

### ISSUE THREAD

**Issue by LiutongZhou** [dmlc/web-data#252]
[web-data/gluonnlp/logs/bert/finetune_squad2.0_large_mx1.6.0rc1.sh](https://github.com/dmlc/web-data/blob/master/gluonnlp/logs/bert/finetune_squad2.0_large_mx1.6.0rc1.sh)

  
on -> python

**Comment by szha** [comment]
@LiutongZhou thanks for reporting. I fixed the issue.
