### ISSUE TITLE
new dataset

### ISSUE THREAD

**Issue by Haseebullah010** [dmlc/web-data#255]
when i am try to test a new pic on this pre trained frcnn but this give me error and not accepting any kind of image other than this

**Comment by szha** [comment]
it's unclear what you mean. if you are using gluon-cv, please post to https://github.com/dmlc/gluon-cv/issues

**Comment by Haseebullah010** [comment]
Hi,    Am Sorry, I have tried my best to explain my problem. But now my problem has been resolved.Thank you soo much for reply. Regard Haseeb Ullah Sent from Mail for Windows 10 From: Sheng ZhaSent: Thursday, July 16, 2020 8:37 AMTo: dmlc/web-dataCc: Haseebullah010; AuthorSubject: Re: [dmlc/web-data] new dataset (#255) it's unclear what you mean. if you are using gluon-cv, please post to https://github.com/dmlc/gluon-cv/issues—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
